#!/bin/bash

function warningmsg () { tput setaf 1; echo "WARNING: $1"; tput sgr0; }
function infomsg () { tput setaf 2; echo "INFO: $1"; tput sgr0; }
function pmsg () { tput setaf 3; echo "$1"; tput sgr0; }

function messagestoday () {
    msgskeys="error|Error|Out of Memory|segfault|DriveReady SeekComplete"
    grep "$(date '+%b %d')" /var/log/messages|egrep "$msgskeys"
}

function printcmdout () {
    # Usage: printcmdout COMMAND WARNINGMSG [TESTCOMMAND]
    if [[ -n $3 ]]; then
	cmdout=$(eval "$3")
    else
	cmdout=$(eval "$1")
    fi
    if [[ -n $cmdout ]]; then
	warningmsg "$2..."
	echo "$cmdout" | head -n10
	nlines=$( echo "$cmdout"|wc -l )
	if [[ $nlines -gt 10 ]]; then
	    pmsg "[...]"
	    pmsg "Only showing first 10 of $nlines lines."
	    pmsg "To see the full output, run \"$1\"."
	fi
    fi
}

function printiptables () {
    printcmdout "$1" "$2" "$1|sed -e '/^target/d' -e '/Chain/d' -e '/^$/d'"
}

if [[ $( whoami ) == "root" ]]; then
    # Check OS version
    if [[ -n $(cat /etc/issue|grep "Red Hat Enterprise Linux ES release 3") ]]; then
	infomsg "Server is running RHEL3."
    elif [[ -n $(cat /etc/issue|grep "Red Hat Enterprise Linux ES release 4") ]]; then
	infomsg "Server is running RHEL4."
    elif [[ -n $(cat /etc/issue|grep "Red Hat Enterprise Linux ES release 5") ]]; then
	infomsg "Server is running RHEL5."
    elif [[ -n $(cat /etc/issue|grep "Debian GNU/Linux") ]]; then
	infomsg "Server is running Debian."
    fi

    # Check for Plesk
    publicip="$(curl -s www.whatismyip.com/automation/n09230945.asp)"
    if [[ ! "$( rpm -q psa )" == "package psa is not installed" ]]; then
	infomsg "This is a Plesk box.
      Plesk URL: https://$publicip:8443/
      Plesk admin password: $(cat /etc/psa/.psa.shadow)"
    else
	infomsg "Public IP: $publicip"
    fi

    # Check for rs-sysmon
    if [[ ! "$( rpm -q rs-sysmon )" == "package rs-sysmon is not installed" ]]; then
	infomsg "rs-sysmon is installed."
    fi

    # Check for interesting syslog messages
    printcmdout messagestoday "The following was logged today in /var/log/messages"

    # Check for a running iptables firewall
    printiptables "iptables -nL" "There is an iptables firewall running"
    printiptables "iptables -nL -t nat" "There are rules in the iptables nat table"
    printiptables "iptables -nL -t mangle" "There are rules in the iptables mangle table"

    # Check the load average in the past hour
    for i in $( sar -q|tail -n6|sed '$d'|awk '{print $5}' ); do
	if [[ ${i/\.*} -gt 5 ]]; then
	    warningmsg "The load average has been above 5 in the past hour."
	    sar -q | head -n3 | tail -n1 && sar -q | tail
	    break
	fi
    done
    if [[ $(who|wc -l) -gt 1 ]]; then
	warningmsg "Other users are logged in."
	who
    fi

    # Check if server has been swapping
    swappts=3
    swapdat=$(mktemp)
    sar -r|sed -e 's/^Average.*//' -e 's/.*RESTART.*//' -e 's/.*kbmemfree.*//' -e '/^$/d'|tail -n$swappts|awk '{ print $10 }' > $swapdat
    if [[ $(cat $swapdat|wc -l) -ge 3 ]]; then
	sdsh=$(mktemp)
	curl -s http://quicksnips.org/sd.sh > $sdsh
	swapsd=$(sh $sdsh $swapdat)
	rm -f $swapdat $sdsh
	if [[ ${swapsd/\.*} -gt 5 ]]; then
	    warningmsg "Server is currently swapping."
	fi
    fi

    # Check available memory
    memavail=$( free -m|sed -n 3p|awk '{ print $4 }' )
    if [[ $memavail -lt 50 ]]; then
	warningmsg "There are only $memavail MB of free memory"
    fi

    # Checking available disk space
    dfroot=$( df -Pm|sed 1d|awk '$6 ~ /^\/$/ { print $4 }' )
    if [[ $dfroot -lt 1024 ]]; then
	warningmsg "The root partition only has $dfroot MB available"
    fi

    # Check MySQL
    if [[ ! $( mysql -e exit 2>/dev/null || echo denied ) == "denied" ]]; then
	mcused=$( mysql -Bse 'show full processlist'|wc -l )
	mctotal=$( mysql -Bse "show variables like '%max_connections%'" | awk '{ print $2 }' )
	let mcleft=$mctotal-$mcused
	if [[ $mcleft -lt 10 ]]; then
	    warningmsg "MySQL connections used/total: $mcused/$mctotal"
	fi
    else
	warningmsg "root can't login to mysql."
    fi

    # Check Apache
    abin=$(netstat -ltnp|awk '$4 ~ /:80$/ { print $7 }'|cut -d / -f 2)
    aroot=$($abin -V|grep "HTTPD_ROOT"|sed 's/.*=\"\(.*\)\"/\1/')
    aconf=$($abin -V|grep "SERVER_CONFIG_FILE"|sed 's/.*=\"\(.*\)\"/\1/')
    amode=$($abin -l|egrep "worker.c|prefork.c"|sed 's/ *\(.*\)\.c/\1/')
    if [[ -n $aroot ]]; then
	aconfpath=$aroot/$aconf
    else
	aconfpath=$aconf
    fi
    actotal=$(sed -n "/<IfModule.*$amode/,/<\/IfModule/p" $aconfpath|grep -i "MaxClients"|sed '/^#.*/d'|awk '{print $2}')
    acused=$( pgrep $abin|wc -l )
    let acleft=$actotal-$acused
    if [[ $acleft -lt 10 ]]; then
	warningmsg "Apache MaxClients used/total: $acused/$actotal"
    fi
    aclargestkb=$(for pid in $(pgrep $abin); do printf "%d\n" "$(pmap -d $pid|awk '$3 ~ /private/ { print $4 }'|sed 's/K//')"; done | sort -nr | head -n1)
    memkbavail=$(free|sed -n 2p|awk '{ print $2 }')
    let amaxmemkb=$aclargestkb*$actotal
    let acrecommend=$memkbavail/$aclargestkb
    if [[ $amaxmemkb -gt $memkbavail ]]; then
	warningmsg "Apache is configured to use $amaxmemkb kB of memory.  Only $memkbavail kB of memory are installed.  MaxClients should be lowered from $actotal to $acrecommend."
    fi
else
    echo "server-healthcheck should be run as root."
fi
